### ISSUE TITLE
Account page functionality

### ISSUE THREAD

**Issue by tycary** [CodeAjaxDM/Wizards_of_the_Hills#18]
# Overview
The account page needs functionality added. When a user clicks Account, the page should be populated with their content and other items the database.
## Requirements
On account page load:
* Purchased content is displayed with download buttons
* Supported authors are displayed with links to their sites

**Comment by gracecovarrubias** [comment]
Account paths need to be added to Item database under authorWebsite, and names under authorName, in order to link the Items to the creator. Account pages then need to read through Item database, find which Items belong to them, and display them.
