### ISSUE TITLE
Content Creator page functionality

### ISSUE THREAD

**Issue by tycary** [CodeAjaxDM/Wizards_of_the_Hills#19]
# Overview
The your content creator page needs functionality added. When a user clicks on their content creator page link, the page should be populated with their published content and other items the database.
## Requirements
On content creator page load:
* Published content is displayed with prices and edit buttons
* Unpublished content is displayed with prices and edit buttons
* Top contributors are displayed with links to their sites

**Comment by gracecovarrubias** [comment]
Account paths need to be added to Item database under authorWebsite, and names under authorName, in order to link the Items to the creator. Account pages then need to read through Item database, find which Items belong to them, and display them.
